name: Publish
run-name: Publish
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: Clone repo
        uses: actions/checkout@v5
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Lint TypeScript
        run: bun lint:tsc
      - name: Lint Biome
        run: bun lint:biome
      - name: Build
        run: bun run build
      - name: Publish effect-fc
        uses: JS-DevTools/npm-publish@v4
        with:
          package: packages/effect-fc
          access: public
          token: ${{ secrets.NPM_TOKEN }}
          registry: https://registry.npmjs.org
