name: Test build
run-name: Test build
on:
  pull_request:

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: "22"
      - name: Clone repo
        uses: actions/checkout@v5
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Lint TypeScript
        run: bun lint:tsc
      - name: Lint Biome
        run: bun lint:biome
      - name: Build
        run: bun run build
      - name: Pack
        run: bun pack
